### ISSUE TITLE
Png image size differs between different screen densities

### ISSUE THREAD

**Issue by CordulaMW** [coil-kt/coil#1053]
Hello,

**Describe the bug**
The images are provided as pngs for the different screen densities (dpi, dpi, xhip, xxhdpi, xxxhdpi).  Before the images were loaded via `BitmapFactory.decodeResource(context.resources, id)` and had the same relative size on devices with different screen densities, also non standard one (e.g. 420dpi). 
After migrating to coil the loaded bitmaps differ in the displayed size and appear bigger on devices which do not have a standard screen density.
I would expect to have the same image size for different screen densities as it was with BitmapFactory.

**To Reproduce**
The image has to be saved as pngs in the folders for the different screen densities (as described here: https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp). Then load this image with coil setting the size to OriginalSize. Do not set it directly inside an image view, instead convert the drawable to a bitmap. Compare the size with the bitmap size loaded with BitmapFactory. 
This only applies if the used device does not have a standard screen density, e.g. 420 dpi. 
See for my implementation https://gist.github.com/CordulaMW/495a5c313198e04671cedf41e8373fbb

**Logs/Screenshots**
<img width="200" src="https://user-images.githubusercontent.com/48513234/146935532-92e7ab25-ded0-435b-91c5-de1e5cd352dc.png">

**Version**
io.coil-kt:coil-base:1.4.0
Does only appear on devices with non standard screen density, e.g. Pixel 3a (440dpi) or Pixel 2 (420dpi)

**Comment by colinrtwhite** [comment]
Can you test with the latest 2.0.0 alpha and see if that fixes the issue? This may already be fixed in the `main` branch.

**Comment by CordulaMW** [comment]
I checked it with version 2.0.0-alpha05, but the issue still exists there.
