### ISSUE TITLE
Coil fails to load image with a native crash on emulator

### ISSUE THREAD

**Issue by tedlefter** [coil-kt/coil#178]
**Describe the bug**
A particular image is failing to load when using Coil.
The app crashes with a native crash.

Image causing this: https://d2lnr5mha7bycj.cloudfront.net/product-image/file/primary_2a461463-ca35-44b6-82b7-426375c8f70c.png

**Expected behavior**
The image should load and be displayed in the ImageView

**To Reproduce**
Load the above-mentioned image into an ImageView

**Version**
The issue is reproducible on the API 26 Emulator.

**Logs/Screenshots**
```2019-11-18 19:12:00.044 1723-1743/system_process E/memtrack: Couldn't load memtrack module
2019-11-18 19:12:15.027 2273-3221/com.google.android.gms E/ZappPhoneskyConn: Unable to bind to Phonesky
2019-11-18 19:12:15.069 1580-1955/? E/OMXNodeInstance: setConfig(0xe64a1080:google.mp3.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2019-11-18 19:12:15.069 1580-1955/? E/OMXNodeInstance: getConfig(0xe64a1080:google.mp3.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2019-11-18 19:12:21.353 3957-5211/com.instacart.instashopper.v2.dev E/EGL_emulation: tid 5211: eglCreateImageKHR(1978): error 0x300c (EGL_BAD_PARAMETER)
2019-11-18 19:12:21.509 5921-5362/? A/google-breakpad: Microdump skipped (uninteresting)
2019-11-18 19:12:21.543 3957-5362/com.instacart.instashopper.v2.dev A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x28 in tid 5362 (DefaultDispatch)
2019-11-18 19:12:21.588 3957-5211/com.instacart.instashopper.v2.dev E/EGL_emulation: tid 5211: eglCreateImageKHR(1978): error 0x300c (EGL_BAD_PARAMETER)
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: Build fingerprint: 'Android/sdk_gphone_x86_64/generic_x86_64:8.0.0/OSR1.180418.019/5598391:userdebug/dev-keys'
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: Revision: '0'
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: ABI: 'x86_64'
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: pid: 3957, tid: 5362, name: DefaultDispatch  >>> com.instacart.instashopper.v2.dev <<<
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x28
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: Cause: null pointer dereference
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     rax 00007eab42d243c0  rbx 0000000000000002  rcx 00007eab42d243c0  rdx 0000000070ce2340
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     rsi 0000000000000926  rdi ffffffffffffffe8
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     r8  0000000000000000  r9  00000000ffffffff  r10 00007eab40d50888  r11 0000000000000246
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     r12 0000000000000000  r13 0000000000000000  r14 0000000000000000  r15 00007eab42c93280
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     cs  0000000000000033  ss  000000000000002b
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     rip 00007eab659f3891  rbp 0000000000000000  rsp 00007eab367f1480  eflags 0000000000010206
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG: backtrace:
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #00 pc 0000000000130891  /system/lib64/libandroid_runtime.so (_ZN7android6bitmap12createBitmapEP7_JNIEnvPNS_6BitmapEiP11_jbyteArrayP8_jobjecti+81)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #01 pc 0000000000136bc2  /system/lib64/libandroid_runtime.so (_ZL8doDecodeP7_JNIEnvP18SkStreamRewindableP8_jobjectS4_+4850)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #02 pc 0000000000ae852b  /system/framework/x86_64/boot-framework.oat (offset 0x5e6000) (android.graphics.BitmapFactory.nativeDecodeStream [DEDUPED]+331)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #03 pc 00000000005c9f56  /system/lib64/libart.so (art_quick_invoke_static_stub+806)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #04 pc 000000000014366d  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+253)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #05 pc 000000000030c3fa  /system/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+330)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #06 pc 000000000030621c  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+828)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #07 pc 00000000005b0cb1  /system/lib64/libart.so (MterpInvokeStatic+497)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #08 pc 00000000005b9e19  /system/lib64/libart.so (artMterpAsmInstructionStart+14489)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #09 pc 00000000002e477a  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+474)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #10 pc 00000000002eb004  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #11 pc 0000000000306204  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+804)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #12 pc 00000000005b0cb1  /system/lib64/libart.so (MterpInvokeStatic+497)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #13 pc 00000000005b9e19  /system/lib64/libart.so (artMterpAsmInstructionStart+14489)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #14 pc 00000000002e477a  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+474)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #15 pc 00000000002eb004  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #16 pc 0000000000306204  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+804)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #17 pc 00000000005b0cb1  /system/lib64/libart.so (MterpInvokeStatic+497)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #18 pc 00000000005b9e19  /system/lib64/libart.so (artMterpAsmInstructionStart+14489)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #19 pc 00000000002e477a  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+474)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #20 pc 00000000002eb004  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #21 pc 0000000000307299  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+825)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #22 pc 00000000005b22e3  /system/lib64/libart.so (MterpInvokeInterfaceRange+1731)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #23 pc 00000000005ba199  /system/lib64/libart.so (artMterpAsmInstructionStart+15385)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #24 pc 00000000002e477a  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+474)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #25 pc 00000000005a1705  /system/lib64/libart.so (artQuickToInterpreterBridge+1365)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #26 pc 00000000005d421c  /system/lib64/libart.so (art_quick_to_interpreter_bridge+140)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #27 pc 000000000011a782  /dev/ashmem/dalvik-jit-code-cache (deleted)
2019-11-18 19:12:23.035 1584-1584/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones//tombstone_00
2019-11-18 19:12:23.072 1436-2069/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property```

**Comment by colinrtwhite** [comment]
Thanks, I think this might be an issue with the emulator since it isn't reproducible on a physical device, but will take a look.

**Comment by mario** [comment]
Seems like an issue with Hardware graphics emulation on API 26 emulator (which I can reproduce). 

```
2020-01-05 20:04:50.031 6834-6858/coil.sample E/EGL_emulation: tid 6858: eglCreateImageKHR(1877): error 0x300c (EGL_BAD_PARAMETER)
2020-01-05 20:04:50.031 6834-6858/coil.sample W/OpenGLRenderer: Could not create EGL image, err =EGL_BAD_PARAMETER
2020-01-05 20:04:50.032 6834-6857/coil.sample A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1c in tid 6857 (DefaultDispatch)
```

Could you try with Graphics set to Software pls @tedlefter?

**Comment by mario** [comment]
I confirm that the fix is in the following:

```
            load("https://d2lnr5mha7bycj.cloudfront.net/product-image/file/primary_2a461463-ca35-44b6-82b7-426375c8f70c.png") {
                allowHardware(false)
            }
```

So what you want to do @tedlefter is set allowHardware to false and it'll all work.

@colinrtwhite if you feel this resolves the issue, close it (as I have no authority to do it)

**Comment by colinrtwhite** [comment]
Is there a way for us to work around this inside Coil? Also if I remember correctly Glide loads that image correctly in the emulator.

**Comment by mario** [comment]
@colinrtwhite yup, fix is here: https://github.com/coil-kt/coil/pull/229

**Comment by colinrtwhite** [comment]
@mario I'm still able to reproduce this in `a0872f9` (and on master). It looks like `View.isHardwareAccelerated` returns true.

**Comment by mario** [comment]
@colinrtwhite I'll take a look (probably tomorrow) - I tested this quite a few times.

**Comment by colinrtwhite** [comment]
Thanks! No rush.

**Comment by mario** [comment]
@colinrtwhite there's a PR now which should fix this.

**Comment by andreevdenis** [comment]
Got here from Google search as I'm experiencing the same with Coil 2.2.2 on emulator. Works fine on phisical device. 

allowHardware(true/false) - doesn't make any difference. 

Trying to load: https://prod-sensor-profile-pictures.s3.eu-central-1.amazonaws.com/48fd5429-433a-473d-9d34-74b7d25380fa.jpg

**Comment by francescopedronomnys** [comment]
Commenting this closed issue (cannot reopen it) as this still happens using `io.coil-kt:coil-compose:2.7.0` on an API 26 emulator.
implementation of RequestService's `fun isConfigValidForHardware` on 2.7.0 checks
```if (target is ViewTarget<*> [...]```
but this is the type of `target` if I place a breakpoint on that line
```coil.compose.AsyncImagePainter$updateRequest$$inlined$target$default$1@29ff360```
so that if is false.

If I change my ImageRequest setting `allowHardware(false)` it doesn't fail anymore, but I would like it to use hardware accelaration when available.
